name: Docker Image ARM build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: klarulor
          password: ${{ secrets.DOCKERHUB_KLARULOR_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
          name: Run Buildx (push image)      
          if: success()      
          run: |        
            docker buildx build --platform linux/arm64 --tag klarulor/anonimbot:arm \ --file ./Dockerfile \        --output type=image,push=true .
